### ISSUE TITLE
yarn fails to install

### ISSUE THREAD

**Issue by mvicari** [iam4x/bobarr#100]
Getting this output:

`Step 6/10 : RUN yarn`
` ---> Running in eb614d55a1ab`
`yarn install v1.22.4`
`[1/4] Resolving packages...`
`[2/4] Fetching packages...`
`error An unexpected error occurred: "https://registry.yarnpkg.com/classnames/-/classnames-2.2.6.tgz: getaddrinfo EAI_AGAIN registry.yarnpkg.com".`
`info If you think this is a bug, please open a bug report with the information provided in "/usr/src/app/yarn-error.log".`
`info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.`
`ERROR: Service 'web' failed to build: The command '/bin/sh -c yarn' returned a non-zero code: 1`

**Comment by ohkeenan** [comment]
Is this after running: `yarn install` ?
What are you trying to accomplish? It doesn't appear `yarn install` is utilized by any part of this project.

**Comment by rasoul-shahriari** [comment]
Hi @mvicari 
I had exactly the same problem like yours on my raspberry server, and I fixed the problem with increasing network time out for yarn.

inside of your docker file(/packages/web/Dockerfile)
line 9: RUN yarn --> RUN yarn --network-timeout 1000000

Please update us with the result

**Comment by iam4x** [comment]
Hi @mvicari this is an issue with yarn registry itself, retry to build the image it may work now.

We will publish already built docker images when bobarr will be released as a first beta!

Right now it's still in active development.

**Comment by iam4x** [comment]
Ok so I've fixed this by publishing images for arm, this was in fact an issue with taking too long to install dependencies (https://github.com/yarnpkg/yarn/issues/4890) and I had to add `--network-timeout 100000` to the yarn install flag :+1:
