### ISSUE TITLE
Problem with the SSL CA cert (path? access rights?)

### ISSUE THREAD

**Issue by memnos** [iam4x/bobarr#110]
Hello,
i'm trying to install Bobarr, but as soon as i try to clone git i have this error.
I'm sure it is a problem of mine, but do you have any suggestion on how to solve, please?

I have this:

`# git clone https://github.com/iam4x/bobarr.git && cd bobarr

Cloning into 'bobarr'...

fatal: unable to access 'https://github.com/iam4x/bobarr.git/': Problem with the SSL CA cert (path? access rights?)
`

**Comment by iam4x** [comment]
Hi @memnos can you try to clone with `$ git clone https://github.com/iam4x/bobarr.git` ?

It's more an issue with your computer and GitHub, HTTPS may work better than SSH.

**Comment by memnos** [comment]
Now it is working git clone, but i have another problem.

I installed Docker with this script https://get.docker.com/
But after i finished i had no docker-compose.
So i tried to install with apt-get.

But when run 
docker-compose up --build --force-recreate -d

I had this error.

ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/


Any idea?

**Comment by iam4x** [comment]
Yes, the docker-compose version is not up to date in registries.

* `$ sudo apt remove docker-compose`
* `$ sudo curl -L "https://github.com/docker/compose/releases/download/1.26.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose`
* `$ sudo chmod +x /usr/local/bin/docker-compose`

There's more information on how you can install docker-compose directly on their website: https://docs.docker.com/compose/install/

**Comment by memnos** [comment]
OK tnx know all is working
