### ISSUE TITLE
Use haugene/docker-transmission-openvpn instead of separate containers in order to provide strong vpn killswitching

### ISSUE THREAD

**Issue by kevinvincent** [iam4x/bobarr#141]
Why not use https://github.com/haugene/docker-transmission-openvpn instead of running separate transmission and openvpn containers? 
It has configuration where Transmission is running only when OpenVPN has an active tunnel

**Comment by iam4x** [comment]
Hi @kevinvincent this should already be the case and fixed by this commit https://github.com/iam4x/bobarr/commit/b4789d3aeff4b2a37a42c8f2906e547d5121c2b0

Some people don't want to use the VPN so I have to use two different containers.
