### ISSUE TITLE
Missing season torrent will block the rename and link, for single episode 

### ISSUE THREAD

**Issue by qqnc** [iam4x/bobarr#153]
When I search and download a season, and the system found a wrong season (or another tv show). therefore I decided to replace one by one, and remove the wrong full season downloading in transmission.

The system will throw error at 

`const isComplete = transmissionTorrent.percentDone === 1;`

in refresh-torrent.processor.ts

`Cannot read property 'percentDone' of undefined`

Because there's no season torrent exists in transmission client, thus transmissionTorrent is undefined, and rest of the process will break.

I think it needs to check the object before getting percentDone, or any suggestion?  I'm trying to learn the code from today, see if I can help in the feature.

I temporarily add const isComplete = !! transmissionTorrent && transmissionTorrent.percentDone === 1;
to by pass it.

**Comment by iam4x** [comment]
Hey @qqnc that is a pretty good fix, can you open a PR and then I will be happy to do a code review and help you out 👍

**Comment by iam4x** [comment]
And this is linked to #50 because bobarr is downloading a season pack but it can't allow to select another season pack or to stop the download.

**Comment by qqnc** [comment]
thanks, haven't checked this for quite a while
