### ISSUE TITLE
Dockerhub tag

### ISSUE THREAD

**Issue by ocervell** [iam4x/bobarr#163]
Hello ! Would it be possible to publish a tag on the [Docker hub repo](https://registry.hub.docker.com/r/dabbz/bobarr) ? Currently there are no tags which means installation on NAS with Docker support (e.g Synology) has to be done manually using docker-compose. Should not take long to do and would be very helpful !

**Comment by iam4x** [comment]
Hi @ocervell 

I've pushed the api & web images on the docker hub and updated the `docker-compose.yml` to use them 👍 

* https://hub.docker.com/r/iam4x/bobarr-api
* https://hub.docker.com/r/iam4x/bobarr-web

The updated command to start the whole stack =>

`$ docker-compose -f docker-compose.yml -f docker-compose.prod.yml up --force-recreate -d`
