### ISSUE TITLE
Missing info in doc : vpn.conf

### ISSUE THREAD

**Issue by SosthenG** [iam4x/bobarr#28]
I had to rename my xxxxx.ovpn file to **vpn.conf** for the vpn to work, but it is not mentioned anywhere in the README (I had to look at the vpn container logs to understand that).

**Comment by iam4x** [comment]
This might be related to your .ovpn config file, it should be the only file in the folder `packages/vpn`

Could it be related to ?

- https://github.com/dperson/openvpn-client/issues/209
- https://github.com/dperson/openvpn-client/issues/254

**Comment by SosthenG** [comment]
Yes, my credentials for my vpn are stored in a credentials.conf file which I put in the same directory, so probably coming from here, thanks!
Anyway renaming my .ovpn file to vpn.conf resolved the issue without having to move my credentials.conf file.
