### ISSUE TITLE
Add support to Wireguard VPN

### ISSUE THREAD

**Issue by Stinocon** [iam4x/bobarr#38]
It might make sense to switch to Wireguard instead of using OpenVPN for the VPN part, or at most support both.
-Ease of configuration
-Supports the most advanced encryption standards
-More performing than OpenVPN
And the interesting thing is that it is no longer so niche, now the largest VPN providers support it.

FYI:
https://protonvpn.com/blog/wireguard-donation/
https://mullvad.net/en/help/why-wireguard/

**Comment by iam4x** [comment]
Hi, thank you for the feedback.

Yes I'm definitely willing to add wireguard support because of it's low cpu usage.

I'll check what can be done.

**Comment by ohkeenan** [comment]
It's not exactly what you  asked for but #83 if you care to try.
Are you wanting wireguard to mask torrents/transmission or for connecting to another location to access the stack?
