### ISSUE TITLE
support arm docker

### ISSUE THREAD

**Issue by iam4x** [iam4x/bobarr#41]

**Comment by plsnotracking** [comment]
@iam4x any chance for an arm (raspberrypi) build for `armhf`?

https://hub.docker.com/u/arm32v7 -  we can base it off of this?

**Comment by deikka** [comment]
What about arm32v6 (marvel)? WD Mycloud users would be happy :)

**Comment by iam4x** [comment]
Docker images are published for arm, theses are supported archs => `linux/amd64, linux/arm/v6, linux/arm/v7, linux/arm64`
