### ISSUE TITLE
Multiple Quality downloads 

### ISSUE THREAD

**Issue by LintHart** [iam4x/bobarr#55]
Hi Iam4x, a strong feature would be to attach multiple quality profiles to a movie/show for more than 1 copy. Example a 4K HDR profile and a 1080p copy for external streaming. 

My fingers are crossed :)

Great work so far

**Comment by iam4x** [comment]
Hi @LintHart, thank you for the feedback.

This has been requested a lot and detailed here #46
Could you comment in that issue if the specs are good for your usage?

I'll close this issue since it's duplicated.
