### ISSUE TITLE
not downloading ?

### ISSUE THREAD

**Issue by adrienjoly** [iam4x/bobarr#57]
Hi!

After following the instructions from the README, I'm running bobarr on my Mac, without VPN.

But I don't see anything being downloaded...

How to reproduce:

1. go to http://localhost:3000/search
2. click on "ad astra", to add it to the library
3. make sure that it's listed in http://localhost:3000/library/movies
4. in the download section of http://localhost:4000/jobs, I see "1 completed" and "1 delayed"

![image](https://user-images.githubusercontent.com/531781/79075348-9ca1ca00-7cf2-11ea-92a8-c289007e9310.png)

![image](https://user-images.githubusercontent.com/531781/79075368-b6431180-7cf2-11ea-8b03-d9b2ba591f70.png)

5. and I don't see anything in transmission: http://localhost:9091/transmission/web/

## expected behavior

I expected that the download would start immediately, or get some feedback about when it's supposed to start, or about any error that may have happened.

**Comment by iam4x** [comment]
Hi, thank you for the detailed issue. 

* Did you correctly add your torrent account in Jackett so it can search?
* Did you correctly link your jackett api key to bobarr?
* Do you see "ad astra" in "in your movies library" as missing?

**Comment by adrienjoly** [comment]
Oh, I didn't know Jackett, and I didn't know that I needed to setup an account 😅

Thanks for your reply, I'll hope to try that soon!

**Comment by iam4x** [comment]
Jackett is a service that is started in the docker-compose stack of bobarr, you just need to setup your preferred torrent trackers so bobarr can searchs into them.

**Comment by adrienjoly** [comment]
The downloaded bytes increase rapidly since I added my tracker account in jacket and clicked "download missing files" button:

![image](https://user-images.githubusercontent.com/531781/79375127-6c5b6500-7f58-11ea-9316-a06ac307c08c.png)

So it seems to work!
