### ISSUE TITLE
Settings page : There's no field to update the jackett API key

### ISSUE THREAD

**Issue by mune360** [iam4x/bobarr#65]
Hi !

In the installation steps : 
""""
Installation

    Clone the repo $ git clone https://github.com/iam4x/bobarr.git && cd bobarr

    Set PUID and PGID in .env (see .env for explanation)

    Start the bobarr minimal stack $ docker-compose up --build -d (see below to add vpn)

    Go to http://localhost:9117 and copy the API Key in top right corner

    Go to http://localhost:3000/settings and update the jackett API key
"""""

The step : "go to .. setting and update the jacket api key" ==> There's no field to update that information.
(see screenshot for proof). ![2020-04-14_13-50-03](https://user-images.githubusercontent.com/10731620/79257251-5f0a8180-7e57-11ea-98b5-5dcef7a94e57.png)

**Test with :** 
Firefox : Linux and Windows
Chrome (on OSX + Android)

**Details**
$ date
Tue Apr 14 14:05:55 EDT 2020

$ git status
On branch master
Your branch is up to date with 'origin/master'.

Running on Docker 
Docker version 19.03.6, build 369ce74a3c

**Comment by iam4x** [comment]
Hi 👋 

Thank you for the bug report, as this has no release yet things can break pretty fast I'm sorry.

You can `$ git pull` and restart it should be fixed.

**Comment by mune360** [comment]
I confirm it is working now after updating. tx for the quick answer
