### ISSUE TITLE
Settings options are blank 

### ISSUE THREAD

**Issue by loekey87** [iam4x/bobarr#66]
I ran into some issues that required me to nuke the entire project, containers, images, volumes etc. I tired to clone the repo, add my vpn settings, user id and then compose with vpn. Runs compose but then shows the following errors:

Status: Downloaded newer image for node:12
 ---> 0c601cba9f11
Step 2/9 : ENV PORT 3000
 ---> Running in 6813f55a3c9c
Removing intermediate container 6813f55a3c9c
 ---> 1960b76219cb
Step 3/9 : EXPOSE 3000
 ---> Running in b6a1d5911d42
Removing intermediate container b6a1d5911d42
 ---> 6e31827e48eb
Step 4/9 : WORKDIR /usr/src/app
 ---> Running in 129aa8bf8e34
Removing intermediate container 129aa8bf8e34
 ---> ef4993876a5e
Step 5/9 : COPY package*.json ./
 ---> d1135873aa71
Step 6/9 : RUN yarn
 ---> Running in 552594b04324
yarn install v1.22.4
info No lockfile found.
[1/4] Resolving packages...
warning antd > omit.js > babel-runtime > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning next > @ampproject/toolbox-optimizer > css > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning next > @ampproject/toolbox-optimizer > css > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning next > @ampproject/toolbox-optimizer > css > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning react-masonry-component > create-react-class > fbjs > core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning @graphql-codegen/cli > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @graphql-codegen/cli > @graphql-toolkit/common > graphql-tools-fork@9.0.1: graphql-tools-fork has been merged into upstream graphql-tools@5
warning @graphql-codegen/cli > @graphql-toolkit/url-loader > graphql-tools-fork@9.0.1: graphql-tools-fork has been merged into upstream graphql-tools@5
warning @graphql-codegen/cli > @graphql-toolkit/core > @graphql-toolkit/schema-merging > graphql-tools-fork@9.0.1: graphql-tools-fork has been merged into upstream graphql-tools@5
warning @graphql-codegen/fragment-matcher > @graphql-codegen/plugin-helpers > @graphql-toolkit/common > graphql-tools-fork@8.9.6: graphql-tools-fork has been merged into upstream graphql-tools@5
warning @graphql-codegen/typescript > @graphql-codegen/visitor-plugin-common > @graphql-toolkit/relay-operation-optimizer > relay-compiler > fbjs > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
[2/4] Fetching packages...
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.12: The platform "linux" is incompatible with this module.
info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @apollo/react-common@3.1.4" has unmet peer dependency "apollo-utilities@^1.3.2".
warning " > styled-components@5.1.0" has unmet peer dependency "react-is@>= 16.8.0".
[4/4] Building fresh packages...

plus

Building api
Step 1/9 : FROM node:12
 ---> 0c601cba9f11
Step 2/9 : ENV PORT 4000
 ---> Running in 687d4cbcad59
Removing intermediate container 687d4cbcad59
 ---> 7e437b28119f
Step 3/9 : EXPOSE 4000
 ---> Running in ff396cb7a00f
Removing intermediate container ff396cb7a00f
 ---> 62141564d8fa
Step 4/9 : WORKDIR /usr/src/app
 ---> Running in d33c2a9af1dc
Removing intermediate container d33c2a9af1dc
 ---> 8fa1f956678f
Step 5/9 : COPY package*.json ./
 ---> 6658d86cf5c9
Step 6/9 : RUN yarn
 ---> Running in 64440b1e0f66
yarn install v1.22.4
info No lockfile found.
[1/4] Resolving packages...
warning @nestjs/graphql > merge-graphql-schemas > @graphql-toolkit/schema-merging > graphql-tools-fork@9.0.1: graphql-tools-fork has been merged into upstream graphql-tools@5
warning @nestjs/graphql > merge-graphql-schemas > @graphql-toolkit/schema-merging > @graphql-toolkit/common > graphql-tools-fork@9.0.1: graphql-tools-fork has been merged into upstream graphql-tools@5
warning request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @nestjs/cli > fork-ts-checker-webpack-plugin > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning @nestjs/cli > fork-ts-checker-webpack-plugin > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning @types/dotenv@8.2.0: This is a stub types definition. dotenv provides its own type definitions, so you do not need this installed.
[2/4] Fetching packages...

the rest of the steps run ok and i'm able to navigate to the bobarr search from there i go to settings and there are no fields for me to adjust. 

I've completely removed docker, tried again and even wiped my linux build and started from scratch still no joy

**Comment by mune360** [comment]
Same issue with settings. I've done it manually :
Go to "graphql" (http://IP:4000/graphql)

First, validate the "jackett" api is empty : 
query {
        getParams
                {jackett_api_key}
}

Then you can update it using "mutation" syntax : 

mutation {
  updateParams(params: {
        key : "jackett_api_key"
        value :"key_from_jackett_api"
  })
  {success,message}
}

It works for me.

**Comment by iam4x** [comment]
Hi 👋 

Thank you for the bug report, as this has no release yet things can break pretty fast I'm sorry.

You can `$ git pull` and restart it should be fixed.
