### ISSUE TITLE
Without Docker?

### ISSUE THREAD

**Issue by mad-tunes** [iam4x/bobarr#68]
I currently run Sonarr/Radarr/Lidarr/Jackett/Transmission on Windows and like the idea of trying out bobarr.
I don't really want to have any duplication of jackett and transmission though, and tend to avoid docker (I'm sure it has great uses, but often feels like unneccessary abstraction and complication).

I understand the 'bundled' nature of the bobarr stack, getting everything talking the first time I installed it all did involve a learning curve.. but is there any way bobarr could be installed/run on windows without docker and the rest of the 'stack'?
..ideally as its own .exe/service as with sonarr/radarr/lidarr, using my existing jackett & transmission?

**Comment by iam4x** [comment]
Hi tahnk you for the feedback, I'm sorry this is not planned and won't be easily doable. This goes against the main idea of bobarr being simple and all included.
