### ISSUE TITLE
Feature request : Calendar of upcoming tvshows based on the actual library

### ISSUE THREAD

**Issue by mune360** [iam4x/bobarr#75]
Hi !
First, I love bobarr. Great job.

Here's another request.

-  As a user I would like to see the upcoming tv episodes
** TVShow name, Episode # or Episode name, and time or airtime

Example : http://pogdesign.co.uk/cat/

**Comment by iam4x** [comment]
Hi thank you! 

Yes I had it before open sourcing the project, I forgot to re-add it on the roadmap. This is definitely in the roadmap!
