### ISSUE TITLE
Cannot add indexer in Jackett

### ISSUE THREAD

**Issue by spoke123** [iam4x/bobarr#79]
On the Jackett page at localhost:9117, nothing happens after clicking '+ Add Indexer' > Selecting a public indexer > Clicking the green + icon. It just takes me back to the main page without adding the indexer. Tried with several public indexers.

Clicking the blue spanner icon next to the public indexer loads a details/config window but clicking 'Okay' leads to a never ending spinning arrows icon.

**Comment by stratacorps** [comment]
I have the same issue. Using VPN...

Steps to reproduce:

1. git clone https://github.com/iam4x/bobarr.git
2. cd bobarr
3. Created opvn configuration (PIA), copied opvn file to packages/vpn
4. docker-compose -f docker-compose.yml -f docker-compose.vpn.yml up -d
5. browser: http://localhost:9117 (redirected to localhost:9117/UI/Dashboard
6. + Add indexer
7. located a public indexer for testing, click on + and just return to Jackett dashboard, no indexer added.
8. click on the configure for a index, click Okay, and just sits there, spinning

bobarr-jacket log:

04-17 07:46:50 Info Adding aggregate indexer
04-17 07:46:50 Warn No XML encryptor configured. Key {d9f68781-aeeb-4696-9e3a-b430638732b1} may be persisted to storage in unencrypted form.
04-17 07:46:50 Info Jackett startup finished in 20.078 s
Hosting environment: Production
Content root path: /app/Jackett/Content
Now listening on: http://[::]:9117
Application started. Press Ctrl+C to shut down.
04-17 08:46:43 Info Updates are disabled via --NoUpdates.
04-17 21:10:40 Info Manual search for "mission impossible" on with 0 results.
04-17 21:13:09 Info Manual search for "mission impossible ghost protocol 2011" on with 0 results.

bobarr-jackett-web:

Generating a RSA private key
..........+++++
writing new private key to '/etc/nginx/ssl/privkey.pem'
-----

**Comment by iam4x** [comment]
Hi, I'm having also issues with jackett and vpn for now. I guess it's not a good solution to route jackett traffic through the vpn. I'll disable it.

**Comment by iam4x** [comment]
Can you pull master and confirm me it's working now?
