### ISSUE TITLE
Use lockfiles when installing dependencies in Docker (yarn.lock)

### ISSUE THREAD

**Issue by kleyu** [iam4x/bobarr#81]
Hi, I noticed that the project uses yarn to manage dependencies. Wouldn't it be safer to make use of `yarn.lock` when resolving dependencies? 

Change is needed here:
https://github.com/iam4x/bobarr/blob/0793e7473a4f50fdb7df77ba5668240d212584c9/packages/web/Dockerfile#L7

and here:
https://github.com/iam4x/bobarr/blob/0793e7473a4f50fdb7df77ba5668240d212584c9/packages/api/Dockerfile#L7

It should look like `COPY package.json yarn.lock ./`

**Comment by iam4x** [comment]
Oh yes, definitely good catch 👍
