### ISSUE TITLE
Feature request : Add an authentication page

### ISSUE THREAD

**Issue by rchoffardet** [iam4x/bobarr#88]
I installed Bobarr on my dedicated server. The only way to prevent the whole planet from connecting to it is to block the ports with a firewall.
Would it be possible to protect access with an authentication page?

**Comment by iam4x** [comment]
Hi @rchoffardet yes this is planned with #34 it will be my next priority after beta 2 roadmap. You can check the roadmap here => https://github.com/iam4x/bobarr/projects/1
