### ISSUE TITLE
[Discover] Movies year filter is not working

### ISSUE THREAD

**Issue by iam4x** [iam4x/bobarr#90]
Hi @rasoul-shahriari I've merge the PR to make bug reports it will be easier to iterate on the feature, so here's my first bug report.

![Screenshot 2020-04-24 at 11 20 15](https://user-images.githubusercontent.com/893837/80196412-b067fd00-861d-11ea-9b26-f870e4dd34d9.png)

**Comment by rasoul-shahriari** [comment]
I will fix it soon
