### ISSUE TITLE
track files in database

### ISSUE THREAD

**Issue by iam4x** [iam4x/bobarr#96]
We need to track files download and their path.

* It will enable refactoring on delete movie/tvshow from library.
* We can save file details in database after download (#76)
* It's a first step to allow multiple files download per media (#46)

**Comment by mune360** [comment]
Bonjour ! Could this lead to display the list of files (download completed) in the bobarr GUI per tvShow ?

**Comment by iam4x** [comment]
Hi @mune360 no, this was done today #106
